name: jeraljunto
description: "Junte jeral pra curtir o carnaval "
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  image_picker: ^1.0.7
  image: ^4.1.7
  flutter_riverpod: ^2.5.1
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - web/icons/logo_512.png
    - web/icons/logo_192.png

  uses-material-design: true
